services:
  sevault-plugin:
    build: .
    privileged: true
    network_mode: host
    volumes:
      #- /run/docker/plugins:/run/docker/plugins   # <-- THIS WONT WORK ON MACOS
      - /var/lib/sevault:/var/lib/sevault
    environment:
      - LOG_LEVEL=debug

  test-nfs-client:
    image: alpine:3.20
    depends_on:
      - sevault-plugin
    volumes:
      - testvol:/mnt

volumes:
  testvol:
    driver: sevault
    driver_opts:
      host: "127.0.0.1"
      export: "/tmp"
