version: "3.9"

services:
  sevault-plugin:
    build: .
    privileged: true
    network_mode: host
    volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /var/lib/sevault:/var/lib/sevault
