services:
  test-nfs-client:
    image: alpine:3.20
    # depends_on: # This should be removed or commented if sevault-plugin is removed
      # - sevault-plugin #
    volumes:
      - testvol:/mnt

volumes:
  testvol:
    driver: sevault
    driver_opts:
      host: "127.0.0.1"
      export: "/tmp"
