name: sevault-plugin-release

on:
  push:
    tags: ["v*"]          # runs only for version tags (v0.1.2, v1.0.0 …)

jobs:
  build-publish-plugin:
    runs-on: ubuntu-latest
    env:
      # Single-arch rootfs image (linux/amd64) built just for assembling the plugin
      ROOTFS_IMG: sevault-rootfs:${{ github.sha }}
      # Final plugin reference pushed to GHCR, versioned by Git tag
      PLUGIN_REF: ghcr.io/${{ github.repository }}/sevault-plugin:${{ github.ref_name }}

    steps:
    # 1. Checkout code -------------------------------------------------
    - uses: actions/checkout@v4

    # 2. Set up QEMU + Buildx (stable) ---------------------------------
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # 3. Login to GHCR --------------------------------------------------
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4. Build a rootfs OCI image (single arch is enough for plugin) ----
    - name: Build rootfs image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --file Dockerfile.plugin \
          --tag $ROOTFS_IMG \
          --load .                       # load into local engine

    # 5. Assemble plugin directory -------------------------------------
    - name: Assemble plugin
      run: |
        mkdir -p plugin/rootfs
        # export the container filesystem into rootfs/
        cid=$(docker create $ROOTFS_IMG)
        docker export "$cid" | tar -C plugin/rootfs -xf -
        docker rm "$cid"
        # copy static plugin config
        cp plugin-config.json plugin/config.json

    # 6. Create the Docker plugin locally ------------------------------
    - name: Create local plugin
      run: |
        docker plugin create $PLUGIN_REF ./plugin
        # keep it disabled; we only need it for push

    # 7. Push plugin to GHCR -------------------------------------------
    - name: Push plugin to registry
      run: |
        docker plugin push $PLUGIN_REF

    # 8. Show result (debug) -------------------------------------------
    - name: List local plugins
      run: docker plugin ls
