name: plugin-release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLUGIN_REF: ghcr.io/${{ github.repository }}/sevault-plugin:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU & Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0-rc1 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build Sevault plugin
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output type=docker-plugin,name=$PLUGIN_REF,alias=sevault \
            --file Dockerfile.plugin \
            .

      - name: Push Sevault plugin
        run: |
          docker plugin push $PLUGIN_REF